- name: install openvpn and easy-rsa
  apt:
    update_cache: yes
    state: latest
    pkg:
      - openvpn
      - easy-rsa
- name: set sysctl net.ipv4.ip_forward=1
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.ip_forward='
    line: net.ipv4.ip_forward=1

# files for openvpn
- name: openvpn server site config
  copy:
    src: templates/openvpn-server.conf
    dest: /etc/openvpn/this_server.conf
    owner: root
    group: root
    mode: 0644
