# works on Ubuntu 24.04 LTS
- name: add user andreas
  ansible.builtin.user:
    name: andreas
    comment: Andreas Ott K6OTT
    uid: 1112
    group: staff
    create_home: yes
    shell: /bin/bash
    groups: adm,sudo
    append: yes

- name: create ~/.ssh directory
  ansible.builtin.file:
    path: /home/andreas/.ssh/
    state: directory
    mode: '0700'
- name: copy ssh key file for user
  copy:
    src: templates/andreas.ssh.key
    dest: /home/andreas/.ssh/authorized_keys
    owner: andreas
    group: andreas
    mode: '0600'
